version: '3.8'

services:
  api:
    build: .
    container_name: "dispatch305-flask-backend-api"
    # volumes:
    #   - ./:/usr/src/app/
    ports:
      - 5000:5050
    env_file:
      - ./config/.env
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker_dispatch305_user
      - POSTGRES_PASSWORD=docker_dispatch305_pass
      - POSTGRES_DB=docker_dispatch305_db

volumes:
  postgres_data:
