"""empty message

Revision ID: c87d9f9c7012
Revises: 
Create Date: 2022-03-09 17:22:32.660633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87d9f9c7012'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('current_plan', sa.Enum('BASICO', 'VIP', name='currentplanstatus'), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requestcargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_cargo_status', sa.Enum('SEARCHING', 'FOUND', 'CANCEL', name='requeststatus'), nullable=True),
    sa.Column('pricing', sa.Float(), nullable=False),
    sa.Column('state_from', sa.String(length=50), nullable=False),
    sa.Column('state_to', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_founded', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'pricing')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requestcargos')
    op.drop_table('users')
    # ### end Alembic commands ###
